image: Visual Studio 2015
version: 1.0.0 (Build {build})

environment: 
  CODE_SIGNING_CERTIFICATE_PASSWORD:
    secure: +Dn/WhvBx1rVgenyg7x+Bg==

install:
  - cmd: GitVersion /output buildserver
  - ps: .\install\install.ps1 -ErrorAction Stop -InformationAction Continue -Verbose

platform:
  - x86

configuration: Single .msi file

build_script:
  - cmd: msbuild metrocontrol.sln

artifacts:
  - path: bin\$(configuration)\$(platform)\ru-RU
    name: msi.compressed
